kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-binding
  namespace: ${NS_WANTED}
subjects:
- kind: User
  name: ${ACCOUNT}
  namespace: ${NS_WANTED}
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

